main: main.cc
	g++ -Wall --std=c++17 $< -o $@

iostte: iostate.cc
	g++ -Wall --std=c++17 $< -o $@
terminalio: terminalio.cc
	g++ -Wall --std=c++17 $< -o $@
related_stream: related_stream.cc
	g++ -Wall --std=c++17 $< -o $@

